name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: 9.4.8 
          cabal-version: 3.10.2.0
      - name: Install hlint
        run: cabal install hlint
      - name: Run hlint
        run: hlint .
        
  test:
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: 9.4.8
          cabal-version: 3.10.2.0
          
      - name: Run tests
        run: cabal test
